ARG BASE_IMAGE="ghcr.io/ublue-os/base-main@sha256:436f616a397e37d94f8e663e1070edfa271f096485026f27787e40cff79b7beb"
FROM "${BASE_IMAGE}" AS kam-suckless

# This stage is responsible for holding onto
# your config without copying it directly into
# the final image
FROM scratch AS stage-files
COPY ./files /files

# Copy modules
# The default modules are inside blue-build/modules
# Custom modules overwrite defaults
FROM scratch AS stage-modules
COPY ./modules /modules

# Bins to install
# These are basic tools that are added to all images.
# Generally used for the build process. We use a multi
# stage process so that adding the bins into the image
# can be added to the ostree commits.
FROM scratch AS stage-bins
COPY --from=ghcr.io/sigstore/cosign/cosign:v3.0.5 \
  /ko-app/cosign /bins/cosign
COPY --from=ghcr.io/blue-build/cli:latest-installer \
  /out/bluebuild /bins/bluebuild
# Keys for pre-verified images
# Used to copy the keys into the final image
# and perform an ostree commit.
#
# Currently only holds the current image's
# public key.
FROM scratch AS stage-keys
COPY cosign.pub /keys/kam-suckless.pub


# Main image
FROM kam-suckless
ARG TARGETARCH
ARG RECIPE=./recipes/recipe.yml
ARG IMAGE_REGISTRY=localhost
ARG BB_BUILD_FEATURES=""
ARG CONFIG_DIRECTORY="/tmp/files"
ARG MODULE_DIRECTORY="/tmp/modules"
ARG IMAGE_NAME="kam-suckless"
ARG BASE_IMAGE="ghcr.io/ublue-os/base-main"
ARG FORCE_COLOR=1
ARG CLICOLOR_FORCE=1
ARG RUST_LOG_STYLE=always
# Key RUN
RUN --mount=type=bind,from=stage-keys,src=/keys,dst=/tmp/keys \
  mkdir -p /etc/pki/containers/ \
  && cp /tmp/keys/* /etc/pki/containers/
# Bin RUN
RUN --mount=type=bind,from=stage-bins,src=/bins,dst=/tmp/bins \
  mkdir -p /usr/bin/ \
  && cp /tmp/bins/* /usr/bin/
RUN --mount=type=bind,from=ghcr.io/blue-build/nushell-image:default,src=/nu,dst=/tmp/nu \
  mkdir -p /usr/libexec/bluebuild/nu \
  && cp -r /tmp/nu/* /usr/libexec/bluebuild/nu/
RUN \
--mount=type=bind,src=.bluebuild-scripts_6fc443c6,dst=/scripts/,Z \
  /scripts/pre_build.sh

# Module RUNs
RUN \
--mount=type=bind,from=stage-files,src=/files,dst=/tmp/files,rw \
--mount=type=bind,from=ghcr.io/blue-build/modules/files:latest,src=/modules,dst=/tmp/modules,rw \
--mount=type=bind,src=.bluebuild-scripts_6fc443c6,dst=/tmp/scripts/,Z \
--mount=type=cache,sharing=locked,dst=/var/cache/rpm-ostree,id=rpm-ostree-cache-kam-suckless-44-stage-kam-suckless \
--mount=type=cache,sharing=locked,dst=/var/cache/libdnf5,id=dnf-cache-kam-suckless-44-stage-kam-suckless \
--mount=type=cache,sharing=locked,dst=/var/cache/zypp,id=zypper-cache-kam-suckless-44-stage-kam-suckless \
--mount=type=cache,sharing=locked,dst=/var/cache/apk,id=apk-cache-kam-suckless-44-stage-kam-suckless \
--mount=type=cache,sharing=locked,dst=/var/cache/apt,id=apt-cache-kam-suckless-44-stage-kam-suckless \
--mount=type=cache,sharing=locked,dst=/var/cache/pacman,id=pacman-cache-kam-suckless-44-stage-kam-suckless \
--mount=type=cache,sharing=locked,dst=/usr/lib/sysimage/cache/pacman,id=pacman-sysimage-cache-kam-suckless-44-stage-kam-suckless \
/tmp/scripts/run_module.sh 'files' '{"type":"files","files":[{"source":"system","destination":"/"}]}'
RUN \
--mount=type=bind,from=stage-files,src=/files,dst=/tmp/files,rw \
--mount=type=bind,from=ghcr.io/blue-build/modules/dnf:latest,src=/modules,dst=/tmp/modules,rw \
--mount=type=bind,src=.bluebuild-scripts_6fc443c6,dst=/tmp/scripts/,Z \
--mount=type=cache,sharing=locked,dst=/var/cache/rpm-ostree,id=rpm-ostree-cache-kam-suckless-44-stage-kam-suckless \
--mount=type=cache,sharing=locked,dst=/var/cache/libdnf5,id=dnf-cache-kam-suckless-44-stage-kam-suckless \
--mount=type=cache,sharing=locked,dst=/var/cache/zypp,id=zypper-cache-kam-suckless-44-stage-kam-suckless \
--mount=type=cache,sharing=locked,dst=/var/cache/apk,id=apk-cache-kam-suckless-44-stage-kam-suckless \
--mount=type=cache,sharing=locked,dst=/var/cache/apt,id=apt-cache-kam-suckless-44-stage-kam-suckless \
--mount=type=cache,sharing=locked,dst=/var/cache/pacman,id=pacman-cache-kam-suckless-44-stage-kam-suckless \
--mount=type=cache,sharing=locked,dst=/usr/lib/sysimage/cache/pacman,id=pacman-sysimage-cache-kam-suckless-44-stage-kam-suckless \
/tmp/scripts/run_module.sh 'dnf' '{"type":"dnf","repos":{"copr":["atim/starship"]},"install":{"packages":["greetd","tuigreet","xorg-x11-server-Xorg","xorg-x11-xinit","xorg-x11-xauth","xsetroot","xrandr","gcc","make","pkgconf","libX11-devel","libXft-devel","libXinerama-devel","libXrender-devel","git","vim","emacs","tmux","curl","wget","fastfetch"]},"remove":{"packages":["firefox","firefox-langpacks"]}}'
RUN \
--mount=type=bind,from=stage-files,src=/files,dst=/tmp/files,rw \
--mount=type=bind,from=ghcr.io/blue-build/modules/default-flatpaks:latest,src=/modules,dst=/tmp/modules,rw \
--mount=type=bind,src=.bluebuild-scripts_6fc443c6,dst=/tmp/scripts/,Z \
--mount=type=cache,sharing=locked,dst=/var/cache/rpm-ostree,id=rpm-ostree-cache-kam-suckless-44-stage-kam-suckless \
--mount=type=cache,sharing=locked,dst=/var/cache/libdnf5,id=dnf-cache-kam-suckless-44-stage-kam-suckless \
--mount=type=cache,sharing=locked,dst=/var/cache/zypp,id=zypper-cache-kam-suckless-44-stage-kam-suckless \
--mount=type=cache,sharing=locked,dst=/var/cache/apk,id=apk-cache-kam-suckless-44-stage-kam-suckless \
--mount=type=cache,sharing=locked,dst=/var/cache/apt,id=apt-cache-kam-suckless-44-stage-kam-suckless \
--mount=type=cache,sharing=locked,dst=/var/cache/pacman,id=pacman-cache-kam-suckless-44-stage-kam-suckless \
--mount=type=cache,sharing=locked,dst=/usr/lib/sysimage/cache/pacman,id=pacman-sysimage-cache-kam-suckless-44-stage-kam-suckless \
/tmp/scripts/run_module.sh 'default-flatpaks' '{"type":"default-flatpaks","configurations":[{"notify":true,"scope":"system","install":["org.mozilla.firefox","org.gnome.Loupe"]},{"scope":"user"}]}'
RUN \
--mount=type=bind,from=stage-files,src=/files,dst=/tmp/files,rw \
--mount=type=bind,from=ghcr.io/blue-build/modules/signing:latest,src=/modules,dst=/tmp/modules,rw \
--mount=type=bind,src=.bluebuild-scripts_6fc443c6,dst=/tmp/scripts/,Z \
--mount=type=cache,sharing=locked,dst=/var/cache/rpm-ostree,id=rpm-ostree-cache-kam-suckless-44-stage-kam-suckless \
--mount=type=cache,sharing=locked,dst=/var/cache/libdnf5,id=dnf-cache-kam-suckless-44-stage-kam-suckless \
--mount=type=cache,sharing=locked,dst=/var/cache/zypp,id=zypper-cache-kam-suckless-44-stage-kam-suckless \
--mount=type=cache,sharing=locked,dst=/var/cache/apk,id=apk-cache-kam-suckless-44-stage-kam-suckless \
--mount=type=cache,sharing=locked,dst=/var/cache/apt,id=apt-cache-kam-suckless-44-stage-kam-suckless \
--mount=type=cache,sharing=locked,dst=/var/cache/pacman,id=pacman-cache-kam-suckless-44-stage-kam-suckless \
--mount=type=cache,sharing=locked,dst=/usr/lib/sysimage/cache/pacman,id=pacman-sysimage-cache-kam-suckless-44-stage-kam-suckless \
/tmp/scripts/run_module.sh 'signing' '{"type":"signing"}'
COPY suckless /tmp/suckless
COPY containerfiles/suckless/build-suckless.sh /tmp/

RUN chmod +x /tmp/build-suckless.sh && \
    /tmp/build-suckless.sh


RUN \
--mount=type=bind,src=.bluebuild-scripts_6fc443c6,dst=/scripts/,Z \
  /scripts/post_build.sh

# Labels are added last since they cause cache misses with buildah
LABEL io.artifacthub.package.readme-url="https://raw.githubusercontent.com/blue-build/cli/main/README.md"
LABEL org.blue-build.build-id="7341838a-4d8d-4070-a246-0aedfd626d94"
LABEL org.opencontainers.image.base.digest="sha256:436f616a397e37d94f8e663e1070edfa271f096485026f27787e40cff79b7beb"
LABEL org.opencontainers.image.base.name="ghcr.io/ublue-os/base-main:44"
LABEL org.opencontainers.image.created="2026-07-05T23:01:39.383090503+00:00"
LABEL org.opencontainers.image.description="This is my personal OS image."
LABEL org.opencontainers.image.source=""
LABEL org.opencontainers.image.title="kam-suckless"