name: Build kam-suckless

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Verify checkout
        run: |
          echo "Repository:"
          pwd

          echo
          echo "Submodules:"
          git submodule status

          echo
          echo "Contents of suckless/dwm:"
          ls -la suckless/dwm

          echo
          echo "Makefile?"
          test -f suckless/dwm/Makefile && echo YES || echo NO
